name: puntuaOP-prod

services:
  postgres:
    image: postgres:16-alpine
    container_name: puntuaOP_postgres_prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - puntuaOP_net

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
      args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    container_name: puntuaOP_app_prod
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      AUTH_TRUST_HOST: "true"
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3000:3000"
    security_opt:
      - no-new-privileges:true
    networks:
      - puntuaOP_net

volumes:
  postgres_prod_data:

networks:
  puntuaOP_net:
    driver: bridge